name: CI/CD for Wisecow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: pavithra123456789/wisecow1
  IMAGE_TAG: 001   # your existing tag

jobs:
  deploy:
    runs-on: self-hosted    # your Ubuntu runner labels
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Pull Docker image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Verify kubectl
        run: kubectl version --client

      - name: Set kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f .github/flow/wise-kubernetes-main/cert-issuer.yaml || echo "Issuer skipped"
          kubectl apply -f .github/flow/wise-kubernetes-main/deployment.yaml
          kubectl apply -f .github/flow/wise-kubernetes-main/service.yaml
          kubectl apply -f .github/flow/wise-kubernetes-main/ingress.yaml
          kubectl rollout status deployment/wisecow --timeout=180s
